### ISSUE TITLE
considering the use of magic method __set , __unset , __isset , __get

### ISSUE THREAD

**Issue by KTP95** [NanneHuiges/JSend#11]
so like here https://github.com/alexei/php-jsend/blob/master/JSend.php
this for alowed so like this

$success = JSendResponse::success($data);
$success->myvar = 'hello world jsend';
$success->respond();

**Comment by NanneHuiges** [comment]
hmm, interesting. On one side, this feels a bit double as you've allready set the data when creating the success response, on the other side, it isn't _that_ much extra code.

Wouldn't it be a bit confusing when overriding already set parts in the data-array?

**Comment by KTP95** [comment]
I think that is not feels a bit double , because at creation you has setup the main data, after is do only little edits to value,

I  think is no confusing because in any other part is doing setup of property from external of class.

I sincerally think that this is a best approach , and surelly more OOP.

we must consider the differences.


$success = JSendResponse::success(); // or with $data basic
$success->myvar = 'hello world jsend';
$success->myva2r =123
$success->respond();
--------------------
versus
--------------
$data = array();
$data['myvar'] =  'hello world jsend';
$data['myvar2'] =123;
$success = JSendResponse::success();
$success->respond();

**Comment by NanneHuiges** [comment]
It looks allright, so I think I agree. 
(though I don't consider "surely more OOP" a good argument an sich, but that's a different thing :) )

Won't be having time to do an update this week probably, so if you want this soon, just send me a pull request, otherwise I'll look at it this weekend

**Comment by NanneHuiges** [comment]
This didn't get much attention from me, and doesn't have much traction anymore it seems. Closing this for now, would look at a PR if someone revisits this, but i'm sorta on the fence on this. Not really sure about the usecase....
