### ISSUE TITLE
echo JSendResponse::success(array()) - proceduce data.NULL

### ISSUE THREAD

**Issue by KTP95** [NanneHuiges/JSend#12]
hello,
Its impossible print a empty array in json format, was produced a NULL value

This make conflicts with DataTables - Jquery Plugin

**Comment by NanneHuiges** [comment]
I'm not really sure what you mean to be honest. Could you give a small code example ( http://sscce.org/ ) that shows the behaviour and why you think it's wrong?

As far as I know, `[]` (the empty array) is valid JSON.

**Comment by NanneHuiges** [comment]
Quick test:

```
<?php

include "vendor/autoload.php";

$error = new JSend\JSendResponse('success', array('test'));
echo $error.PHP_EOL;

$error = new JSend\JSendResponse('success', array());
echo $error.PHP_EOL;

$error = new JSend\JSendResponse('success');
echo $error.PHP_EOL;
```

The output of this script is

```
{"status":"success","data":["test"]}
{"status":"success","data":null}
{"status":"success","data":null}
```

And those all look like valid JSON strings to me.

**Comment by KTP95** [comment]
Yeah, question is...

```
$error = new JSend\JSendResponse('success', array());
{"status":"success","data":null}
```
Why not produce ?
`{"status":"success","data":[]}`

**Comment by shkm** [comment]
The null data is within the [JSend spec](https://labs.omniti.com/labs/jsend#Exampleresponsetypes).

**Comment by KTP95** [comment]
therefore, return an empty json-array is against jsend specific?

I not read this on jsend page, sorry.

**Comment by NanneHuiges** [comment]
Currently the code behaves within spec, and I'd rather not change the behaviour without good reason.

There might be a good point to be made for `array()` vs. `null`, but I don't think it would be important enough to change the currently used result.
