### ISSUE TITLE
success() and fail() should not throw InvalidJSendException

### ISSUE THREAD

**Issue by Listeur** [NanneHuiges/JSend#15]
Hello,

Maybe `JSendResponse::success($data);` and `JSendResponse::fail($data);` should not throw `InvalidJSendException` because they can never had an invalid status.

Only `JSendResponse::error($errorMessage, $errorCode, $data);` can thow the Exception in case `$errorMessage` is empty.

**Comment by NanneHuiges** [comment]
That's sort of a "philosophical" question really I think. The constructor gets called and that can throw an Exception. We're not catching anything, so technically this function needs to throw that exception as well. A static analyser would give an error if you don't catch or declare the exception. 

You can look at it like this: from the point of view of the function `success` (that calls the constructor) its an implementation detail  _when_ we get an exception, but it's known that it _could_ throw one, so we can do nothing more then declare it.

I agree that it's annoying that we have this sorta useless exception in there. We could have a

```
try{
}catch (\Exception $e){ // skip}
```
in there, but that's not much prettier, is it?
