### ISSUE TITLE
Empty array converted to null

### ISSUE THREAD

**Issue by btxtiger** [NanneHuiges/JSend#16]
Is it intended that an empty array is converted to null? 
This is a litte confusing as [JSON:API](https://jsonapi.org/format/#fetching-resources-responses) prescribes that. Unfortunately I could not find a similar rule in the JSend spec. But I for me returning the empty array seems to be the "more correct" way, as in JS `!!null === false` and `!![] === true`

**Comment by NanneHuiges** [comment]
I'm not sure why you reference the JSON:API to be honest, but what part of JSend are you referring to? 

Can you provide an example? So some php code that triggers this behaviour, the output you get and the output you expect.

**Comment by btxtiger** [comment]
I referenced JSON:API just as alternative example as it has some kind of similar top level structure and both nest the returned data in `obj.data`.

Example:
```php
return response(JSendResponse::success([]));
```

```json
{
   "status": "success",
   "data": null
}
```

It seems this behavior comes from setting the default value `$data = null`, and PHP interprets `!![]` as `false` in contrast to JS, where `!![]` is `true`:
```php
    /**
     * From the spec:
     * Description: All went well, and (usually) some data was returned.
     * Required   :  data
     *
     * @param array|null $data
     *
     * @return JSendResponse
     * @throws InvalidJSendException
     */
    public static function success(array $data = null): JSendResponse
    {
        return new static(static::SUCCESS, $data);
    }
```

where as 

```php
$data = [];
var_dump(isset($data)); // => (bool) true
```

That means, with setting the `null` parameter default, it will never be possible to have an empty array as value for the data property.

**Comment by NanneHuiges** [comment]
hmm, I'm not sure and I can't find it very quickly, but isn't `data` an object? I think I remember that you provide a list of stuff that's put in the object, so if you provide nothing, you'd get an empty object. An array isn't an object. But i'm not sure if that's stricter then the JSEND spec is. The only examples i find are with data being an object, but i'm not sure if that's correct or not.

**Comment by btxtiger** [comment]
I would expect, the default `null` should be only set, when $data is not set. So the function should look like something like this:
```php
public static function success(array $data): JSendResponse
{
  if (!isset($data)) $data = null;
  return new static(static::SUCCESS, $data);
}
```
Casting as `object` might prevent the interpretation as false, but then the parameter has an incorrect type:
![image](https://user-images.githubusercontent.com/15804690/82914491-dc093a80-9f6f-11ea-9672-e28f754869ed.png)

**Comment by btxtiger** [comment]
I just saw there is a closed old almost similar issue #12 .
If this behavior is still intended from the spec, there is no chance for me to use JSend. But in my opinion the spec is not very clear at this point.

**Comment by NanneHuiges** [comment]
Yeah, the crux is in this I think:

`data: Acts as the wrapper for any data returned by the API call. If the call returns no data (as in the last example), data should be set to null.`

Data is the wrapper around the response, where the response isn't clearly defined. But having the data be an object will make this the only feasible behaviour i think. The only other sollution would be to have it be an array as well, which has all sorts of implications, do you see where I come from? 

In the 'posts' example, wouldn't you have an empty array of 'posts' so your wrapped data could become `data: {  posts : []}` or something similar?

**Comment by btxtiger** [comment]
If data is designated to be an object, nesting the data might be the only valid option. But imo this is a bit useless by design, because this leads to response objects like `{ data: { data: [] } }`. It makes developing the application morge complicated when using special nested names in the data object. The API url should be enough to "label" the parent data response type.
So I'm going to implement it in an other way.
