### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by jagadishnallappa** [NanneHuiges/JSend#18]
Sorry. I might sound very silly. But how do I install this? I don't see a composer command. Or should I use the file directly from the sources folder?

**Comment by NanneHuiges** [comment]
No worries. There doesn't seem to be a composer command listed indeed, but it's just the same as with any package you would use. It's listed on packagist so you can just add it to your `composer.json` file by either

* addin git manually ( https://getcomposer.org/doc/01-basic-usage.md#the-require-key )
* using composer require ( https://getcomposer.org/doc/03-cli.md#require )

The package lives here: https://packagist.org/packages/nannehuiges/jsend

**Comment by jagadishnallappa** [comment]
> No worries. There doesn't seem to be a composer command listed indeed, but it's just the same as with any package you would use. It's listed on packagist so you can just add it to your `composer.json` file by either
> 
> * addin git manually ( https://getcomposer.org/doc/01-basic-usage.md#the-require-key )
> * using composer require ( https://getcomposer.org/doc/03-cli.md#require )
> 
> The package lives here: https://packagist.org/packages/nannehuiges/jsend

Thank you very much!
