### ISSUE TITLE
Require more keys at the same level as data key level.

### ISSUE THREAD

**Issue by jagadishnallappa** [NanneHuiges/JSend#19]
Hi, 

Mate, sorry to trouble you again. Firstly, I thank you very much for this wonderful JSend specification. I was wondering if a status code and a message key could be included in the response on the same level as data and status. Otherwise it would end up like below upon running the following code:

Code:

`return JSendResponse::fail($validator->errors()->all());`

Response:

```
{
    "status": "fail",
    "data": [
        "The display name field is required.",
        "The email has already been taken."
    ]
}
```

Code:
```
$data = [];
$data['message'] = $validator->errors()->all();
return JSendResponse::fail($data);
```

Response:

```
{
    "status": "fail",
    "data": {
        "message": [
            "The display name field is required.",
            "The email has already been taken."
        ]
    }
}
```

Code:

`return JSendResponse::fail($validator->errors()->jsonSerialize());`

Response:

```
{
    "status": "fail",
    "data": {
        "displayName": [
            "The display name field is required."
        ],
        "email": [
            "The email has already been taken."
        ]
    }
}
```

Whilst the above responses work as intended, is it possible to receive something like the following?

```
{
    "status": "fail",
    "statusCode":"Relevant status code like 403 for example"
    "data": "Some data"
    "message":"Relevant message like Account created successfully!"
}

```

Please help. Perhaps there is another way to achieve this. Thank you very much.

**Comment by jagadishnallappa** [comment]
More details: I am using php lumen framework with its validator responding with your specification.

**Comment by jagadishnallappa** [comment]
Pardon me if I'm using the specification wrongly. Please point me in the right direction.

**Comment by NanneHuiges** [comment]
I'm not really sure if we can do this while adhering to the specification: https://github.com/omniti-labs/jsend

The 'data' key is specifically made to contain the data you mention so while there is nothing specifically against flattening it I guess, it doesn't seem to be a JSEND specification anymore?

**Comment by jagadishnallappa** [comment]
> I'm not really sure if we can do this while adhering to the specification: https://github.com/omniti-labs/jsend
> 
> The 'data' key is specifically made to contain the data you mention so while there is nothing specifically against flattening it I guess, it doesn't seem to be a JSEND specification anymore?

Right. I agree. This is what I wanted to hear and confirm. Thank you very much for your quick response. I will make do with your current specification.
